#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManager_Api.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OrderManager")]
	public partial class OrderManagerModelsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertOD_BRANCH(OD_BRANCH instance);
    partial void UpdateOD_BRANCH(OD_BRANCH instance);
    partial void DeleteOD_BRANCH(OD_BRANCH instance);
    partial void InsertOD_CATEGORY(OD_CATEGORY instance);
    partial void UpdateOD_CATEGORY(OD_CATEGORY instance);
    partial void DeleteOD_CATEGORY(OD_CATEGORY instance);
    partial void InsertOD_COMPANY(OD_COMPANY instance);
    partial void UpdateOD_COMPANY(OD_COMPANY instance);
    partial void DeleteOD_COMPANY(OD_COMPANY instance);
    partial void InsertOD_COMPANY_GROUP(OD_COMPANY_GROUP instance);
    partial void UpdateOD_COMPANY_GROUP(OD_COMPANY_GROUP instance);
    partial void DeleteOD_COMPANY_GROUP(OD_COMPANY_GROUP instance);
    partial void InsertOD_ROLE(OD_ROLE instance);
    partial void UpdateOD_ROLE(OD_ROLE instance);
    partial void DeleteOD_ROLE(OD_ROLE instance);
    partial void InsertOR_FUNCTION(OR_FUNCTION instance);
    partial void UpdateOR_FUNCTION(OR_FUNCTION instance);
    partial void DeleteOR_FUNCTION(OR_FUNCTION instance);
    partial void InsertOD_USER(OD_USER instance);
    partial void UpdateOD_USER(OD_USER instance);
    partial void DeleteOD_USER(OD_USER instance);
    #endregion
		
		public OrderManagerModelsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["OrderManagerConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OrderManagerModelsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrderManagerModelsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrderManagerModelsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrderManagerModelsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<OD_BRANCH> OD_BRANCHes
		{
			get
			{
				return this.GetTable<OD_BRANCH>();
			}
		}
		
		public System.Data.Linq.Table<OD_CATEGORY> OD_CATEGORies
		{
			get
			{
				return this.GetTable<OD_CATEGORY>();
			}
		}
		
		public System.Data.Linq.Table<OD_COMPANY> OD_COMPANies
		{
			get
			{
				return this.GetTable<OD_COMPANY>();
			}
		}
		
		public System.Data.Linq.Table<OD_COMPANY_GROUP> OD_COMPANY_GROUPs
		{
			get
			{
				return this.GetTable<OD_COMPANY_GROUP>();
			}
		}
		
		public System.Data.Linq.Table<OD_ORDER> OD_ORDERs
		{
			get
			{
				return this.GetTable<OD_ORDER>();
			}
		}
		
		public System.Data.Linq.Table<OD_PRODUCT> OD_PRODUCTs
		{
			get
			{
				return this.GetTable<OD_PRODUCT>();
			}
		}
		
		public System.Data.Linq.Table<OD_ROLE> OD_ROLEs
		{
			get
			{
				return this.GetTable<OD_ROLE>();
			}
		}
		
		public System.Data.Linq.Table<OR_FUNCTION> OR_FUNCTIONs
		{
			get
			{
				return this.GetTable<OR_FUNCTION>();
			}
		}
		
		public System.Data.Linq.Table<OD_USER> OD_USERs
		{
			get
			{
				return this.GetTable<OD_USER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OD_BRANCH")]
	public partial class OD_BRANCH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Branch_Code;
		
		private string _Branch_Name;
		
		private System.Nullable<int> _Comp_code;
		
		private int _Type;
		
		private string _Email;
		
		private string _Picture;
		
		private string _Address;
		
		private string _Description;
		
		private System.Nullable<decimal> _Phone;
		
		private System.Nullable<System.DateTime> _Apply_End_Date;
		
		private System.Nullable<System.DateTime> _Apply_Start_Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBranch_CodeChanging(int value);
    partial void OnBranch_CodeChanged();
    partial void OnBranch_NameChanging(string value);
    partial void OnBranch_NameChanged();
    partial void OnComp_codeChanging(System.Nullable<int> value);
    partial void OnComp_codeChanged();
    partial void OnTypeChanging(int value);
    partial void OnTypeChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPictureChanging(string value);
    partial void OnPictureChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnPhoneChanging(System.Nullable<decimal> value);
    partial void OnPhoneChanged();
    partial void OnApply_End_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnApply_End_DateChanged();
    partial void OnApply_Start_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnApply_Start_DateChanged();
    #endregion
		
		public OD_BRANCH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Branch_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Branch_Code
		{
			get
			{
				return this._Branch_Code;
			}
			set
			{
				if ((this._Branch_Code != value))
				{
					this.OnBranch_CodeChanging(value);
					this.SendPropertyChanging();
					this._Branch_Code = value;
					this.SendPropertyChanged("Branch_Code");
					this.OnBranch_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Branch_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Branch_Name
		{
			get
			{
				return this._Branch_Name;
			}
			set
			{
				if ((this._Branch_Name != value))
				{
					this.OnBranch_NameChanging(value);
					this.SendPropertyChanging();
					this._Branch_Name = value;
					this.SendPropertyChanged("Branch_Name");
					this.OnBranch_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comp_code", DbType="Int")]
		public System.Nullable<int> Comp_code
		{
			get
			{
				return this._Comp_code;
			}
			set
			{
				if ((this._Comp_code != value))
				{
					this.OnComp_codeChanging(value);
					this.SendPropertyChanging();
					this._Comp_code = value;
					this.SendPropertyChanged("Comp_code");
					this.OnComp_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int NOT NULL")]
		public int Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="VarChar(100)")]
		public string Picture
		{
			get
			{
				return this._Picture;
			}
			set
			{
				if ((this._Picture != value))
				{
					this.OnPictureChanging(value);
					this.SendPropertyChanging();
					this._Picture = value;
					this.SendPropertyChanged("Picture");
					this.OnPictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(100)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apply_End_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Apply_End_Date
		{
			get
			{
				return this._Apply_End_Date;
			}
			set
			{
				if ((this._Apply_End_Date != value))
				{
					this.OnApply_End_DateChanging(value);
					this.SendPropertyChanging();
					this._Apply_End_Date = value;
					this.SendPropertyChanged("Apply_End_Date");
					this.OnApply_End_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apply_Start_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Apply_Start_Date
		{
			get
			{
				return this._Apply_Start_Date;
			}
			set
			{
				if ((this._Apply_Start_Date != value))
				{
					this.OnApply_Start_DateChanging(value);
					this.SendPropertyChanging();
					this._Apply_Start_Date = value;
					this.SendPropertyChanged("Apply_Start_Date");
					this.OnApply_Start_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OD_CATEGORY")]
	public partial class OD_CATEGORY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Category_Code;
		
		private string _Category_Name;
		
		private string _Category_Name_EN;
		
		private int _Branch_code;
		
		private System.Nullable<int> _Sort;
		
		private string _Picture;
		
		private System.Nullable<System.DateTime> _Apply_Start_Date;
		
		private System.Nullable<System.DateTime> _Apply_End_Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCategory_CodeChanging(int value);
    partial void OnCategory_CodeChanged();
    partial void OnCategory_NameChanging(string value);
    partial void OnCategory_NameChanged();
    partial void OnCategory_Name_ENChanging(string value);
    partial void OnCategory_Name_ENChanged();
    partial void OnBranch_codeChanging(int value);
    partial void OnBranch_codeChanged();
    partial void OnSortChanging(System.Nullable<int> value);
    partial void OnSortChanged();
    partial void OnPictureChanging(string value);
    partial void OnPictureChanged();
    partial void OnApply_Start_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnApply_Start_DateChanged();
    partial void OnApply_End_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnApply_End_DateChanged();
    #endregion
		
		public OD_CATEGORY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Category_Code
		{
			get
			{
				return this._Category_Code;
			}
			set
			{
				if ((this._Category_Code != value))
				{
					this.OnCategory_CodeChanging(value);
					this.SendPropertyChanging();
					this._Category_Code = value;
					this.SendPropertyChanged("Category_Code");
					this.OnCategory_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Category_Name
		{
			get
			{
				return this._Category_Name;
			}
			set
			{
				if ((this._Category_Name != value))
				{
					this.OnCategory_NameChanging(value);
					this.SendPropertyChanging();
					this._Category_Name = value;
					this.SendPropertyChanged("Category_Name");
					this.OnCategory_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category_Name_EN", DbType="NVarChar(100)")]
		public string Category_Name_EN
		{
			get
			{
				return this._Category_Name_EN;
			}
			set
			{
				if ((this._Category_Name_EN != value))
				{
					this.OnCategory_Name_ENChanging(value);
					this.SendPropertyChanging();
					this._Category_Name_EN = value;
					this.SendPropertyChanged("Category_Name_EN");
					this.OnCategory_Name_ENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Branch_code", DbType="Int NOT NULL")]
		public int Branch_code
		{
			get
			{
				return this._Branch_code;
			}
			set
			{
				if ((this._Branch_code != value))
				{
					this.OnBranch_codeChanging(value);
					this.SendPropertyChanging();
					this._Branch_code = value;
					this.SendPropertyChanged("Branch_code");
					this.OnBranch_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sort", DbType="Int")]
		public System.Nullable<int> Sort
		{
			get
			{
				return this._Sort;
			}
			set
			{
				if ((this._Sort != value))
				{
					this.OnSortChanging(value);
					this.SendPropertyChanging();
					this._Sort = value;
					this.SendPropertyChanged("Sort");
					this.OnSortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="NVarChar(100)")]
		public string Picture
		{
			get
			{
				return this._Picture;
			}
			set
			{
				if ((this._Picture != value))
				{
					this.OnPictureChanging(value);
					this.SendPropertyChanging();
					this._Picture = value;
					this.SendPropertyChanged("Picture");
					this.OnPictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apply_Start_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Apply_Start_Date
		{
			get
			{
				return this._Apply_Start_Date;
			}
			set
			{
				if ((this._Apply_Start_Date != value))
				{
					this.OnApply_Start_DateChanging(value);
					this.SendPropertyChanging();
					this._Apply_Start_Date = value;
					this.SendPropertyChanged("Apply_Start_Date");
					this.OnApply_Start_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apply_End_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Apply_End_Date
		{
			get
			{
				return this._Apply_End_Date;
			}
			set
			{
				if ((this._Apply_End_Date != value))
				{
					this.OnApply_End_DateChanging(value);
					this.SendPropertyChanging();
					this._Apply_End_Date = value;
					this.SendPropertyChanged("Apply_End_Date");
					this.OnApply_End_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OD_COMPANY")]
	public partial class OD_COMPANY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Comp_Code;
		
		private string _Comp_Name;
		
		private System.Nullable<int> _Group_Comp_code;
		
		private string _Email;
		
		private string _Picture;
		
		private string _Address;
		
		private string _Description;
		
		private System.Nullable<decimal> _Phone;
		
		private System.Nullable<System.DateTime> _Apply_End_Date;
		
		private System.Nullable<System.DateTime> _Apply_Start_Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnComp_CodeChanging(int value);
    partial void OnComp_CodeChanged();
    partial void OnComp_NameChanging(string value);
    partial void OnComp_NameChanged();
    partial void OnGroup_Comp_codeChanging(System.Nullable<int> value);
    partial void OnGroup_Comp_codeChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPictureChanging(string value);
    partial void OnPictureChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnPhoneChanging(System.Nullable<decimal> value);
    partial void OnPhoneChanged();
    partial void OnApply_End_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnApply_End_DateChanged();
    partial void OnApply_Start_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnApply_Start_DateChanged();
    #endregion
		
		public OD_COMPANY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comp_Code", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Comp_Code
		{
			get
			{
				return this._Comp_Code;
			}
			set
			{
				if ((this._Comp_Code != value))
				{
					this.OnComp_CodeChanging(value);
					this.SendPropertyChanging();
					this._Comp_Code = value;
					this.SendPropertyChanged("Comp_Code");
					this.OnComp_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comp_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Comp_Name
		{
			get
			{
				return this._Comp_Name;
			}
			set
			{
				if ((this._Comp_Name != value))
				{
					this.OnComp_NameChanging(value);
					this.SendPropertyChanging();
					this._Comp_Name = value;
					this.SendPropertyChanged("Comp_Name");
					this.OnComp_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Group_Comp_code", DbType="Int")]
		public System.Nullable<int> Group_Comp_code
		{
			get
			{
				return this._Group_Comp_code;
			}
			set
			{
				if ((this._Group_Comp_code != value))
				{
					this.OnGroup_Comp_codeChanging(value);
					this.SendPropertyChanging();
					this._Group_Comp_code = value;
					this.SendPropertyChanged("Group_Comp_code");
					this.OnGroup_Comp_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="VarChar(100)")]
		public string Picture
		{
			get
			{
				return this._Picture;
			}
			set
			{
				if ((this._Picture != value))
				{
					this.OnPictureChanging(value);
					this.SendPropertyChanging();
					this._Picture = value;
					this.SendPropertyChanged("Picture");
					this.OnPictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(100)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apply_End_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Apply_End_Date
		{
			get
			{
				return this._Apply_End_Date;
			}
			set
			{
				if ((this._Apply_End_Date != value))
				{
					this.OnApply_End_DateChanging(value);
					this.SendPropertyChanging();
					this._Apply_End_Date = value;
					this.SendPropertyChanged("Apply_End_Date");
					this.OnApply_End_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apply_Start_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Apply_Start_Date
		{
			get
			{
				return this._Apply_Start_Date;
			}
			set
			{
				if ((this._Apply_Start_Date != value))
				{
					this.OnApply_Start_DateChanging(value);
					this.SendPropertyChanging();
					this._Apply_Start_Date = value;
					this.SendPropertyChanged("Apply_Start_Date");
					this.OnApply_Start_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OD_COMPANY_GROUP")]
	public partial class OD_COMPANY_GROUP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Group_Comp_code;
		
		private string _GRoup_Comp_Name;
		
		private string _Email;
		
		private string _Picture;
		
		private string _Address;
		
		private string _Description;
		
		private System.Nullable<decimal> _Phone;
		
		private System.Nullable<System.DateTime> _Apply_End_Date;
		
		private System.Nullable<System.DateTime> _Apply_Start_Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGroup_Comp_codeChanging(int value);
    partial void OnGroup_Comp_codeChanged();
    partial void OnGRoup_Comp_NameChanging(string value);
    partial void OnGRoup_Comp_NameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPictureChanging(string value);
    partial void OnPictureChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnPhoneChanging(System.Nullable<decimal> value);
    partial void OnPhoneChanged();
    partial void OnApply_End_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnApply_End_DateChanged();
    partial void OnApply_Start_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnApply_Start_DateChanged();
    #endregion
		
		public OD_COMPANY_GROUP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Group_Comp_code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Group_Comp_code
		{
			get
			{
				return this._Group_Comp_code;
			}
			set
			{
				if ((this._Group_Comp_code != value))
				{
					this.OnGroup_Comp_codeChanging(value);
					this.SendPropertyChanging();
					this._Group_Comp_code = value;
					this.SendPropertyChanged("Group_Comp_code");
					this.OnGroup_Comp_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRoup_Comp_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string GRoup_Comp_Name
		{
			get
			{
				return this._GRoup_Comp_Name;
			}
			set
			{
				if ((this._GRoup_Comp_Name != value))
				{
					this.OnGRoup_Comp_NameChanging(value);
					this.SendPropertyChanging();
					this._GRoup_Comp_Name = value;
					this.SendPropertyChanged("GRoup_Comp_Name");
					this.OnGRoup_Comp_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="VarChar(100)")]
		public string Picture
		{
			get
			{
				return this._Picture;
			}
			set
			{
				if ((this._Picture != value))
				{
					this.OnPictureChanging(value);
					this.SendPropertyChanging();
					this._Picture = value;
					this.SendPropertyChanged("Picture");
					this.OnPictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(100)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apply_End_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Apply_End_Date
		{
			get
			{
				return this._Apply_End_Date;
			}
			set
			{
				if ((this._Apply_End_Date != value))
				{
					this.OnApply_End_DateChanging(value);
					this.SendPropertyChanging();
					this._Apply_End_Date = value;
					this.SendPropertyChanged("Apply_End_Date");
					this.OnApply_End_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apply_Start_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Apply_Start_Date
		{
			get
			{
				return this._Apply_Start_Date;
			}
			set
			{
				if ((this._Apply_Start_Date != value))
				{
					this.OnApply_Start_DateChanging(value);
					this.SendPropertyChanging();
					this._Apply_Start_Date = value;
					this.SendPropertyChanged("Apply_Start_Date");
					this.OnApply_Start_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OD_ORDER")]
	public partial class OD_ORDER
	{
		
		private string _Order_Code;
		
		private string _Order_Name;
		
		private string _Order_Name_EN;
		
		private string _Branch_Code;
		
		private System.Nullable<bool> _Active;
		
		private string _Sector;
		
		private System.Nullable<int> _Max_Time;
		
		private System.Nullable<int> _Sort;
		
		private string _Picture;
		
		private System.Nullable<System.DateTime> _Apply_Start_Date;
		
		private System.Nullable<System.DateTime> _Apply_End_Date;
		
		public OD_ORDER()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Order_Code", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Order_Code
		{
			get
			{
				return this._Order_Code;
			}
			set
			{
				if ((this._Order_Code != value))
				{
					this._Order_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Order_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Order_Name
		{
			get
			{
				return this._Order_Name;
			}
			set
			{
				if ((this._Order_Name != value))
				{
					this._Order_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Order_Name_EN", DbType="NVarChar(50)")]
		public string Order_Name_EN
		{
			get
			{
				return this._Order_Name_EN;
			}
			set
			{
				if ((this._Order_Name_EN != value))
				{
					this._Order_Name_EN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Branch_Code", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Branch_Code
		{
			get
			{
				return this._Branch_Code;
			}
			set
			{
				if ((this._Branch_Code != value))
				{
					this._Branch_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sector", DbType="NChar(10)")]
		public string Sector
		{
			get
			{
				return this._Sector;
			}
			set
			{
				if ((this._Sector != value))
				{
					this._Sector = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Max_Time", DbType="Int")]
		public System.Nullable<int> Max_Time
		{
			get
			{
				return this._Max_Time;
			}
			set
			{
				if ((this._Max_Time != value))
				{
					this._Max_Time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sort", DbType="Int")]
		public System.Nullable<int> Sort
		{
			get
			{
				return this._Sort;
			}
			set
			{
				if ((this._Sort != value))
				{
					this._Sort = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="NVarChar(100)")]
		public string Picture
		{
			get
			{
				return this._Picture;
			}
			set
			{
				if ((this._Picture != value))
				{
					this._Picture = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apply_Start_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Apply_Start_Date
		{
			get
			{
				return this._Apply_Start_Date;
			}
			set
			{
				if ((this._Apply_Start_Date != value))
				{
					this._Apply_Start_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apply_End_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Apply_End_Date
		{
			get
			{
				return this._Apply_End_Date;
			}
			set
			{
				if ((this._Apply_End_Date != value))
				{
					this._Apply_End_Date = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OD_PRODUCT")]
	public partial class OD_PRODUCT
	{
		
		private int _Product_Code;
		
		private string _Product_Name;
		
		private string _Product_Name_EN;
		
		private int _Branch_Code;
		
		private System.Nullable<int> _Category_Code;
		
		private System.Nullable<int> _Typical;
		
		private System.Nullable<decimal> _Price;
		
		private System.Nullable<int> _Promotions;
		
		private System.Nullable<System.DateTime> _Promotions_Start_Date;
		
		private System.Nullable<System.DateTime> _Promotions_End_Date;
		
		private System.Nullable<int> _Inventory_Number;
		
		private System.Nullable<int> _Order_Number;
		
		private System.Nullable<int> _Sort;
		
		private string _Picture;
		
		private System.Nullable<System.DateTime> _Apply_Start_Date;
		
		private System.Nullable<System.DateTime> _Apply_End_Date;
		
		public OD_PRODUCT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_Code", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Product_Code
		{
			get
			{
				return this._Product_Code;
			}
			set
			{
				if ((this._Product_Code != value))
				{
					this._Product_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Product_Name
		{
			get
			{
				return this._Product_Name;
			}
			set
			{
				if ((this._Product_Name != value))
				{
					this._Product_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_Name_EN", DbType="NVarChar(100)")]
		public string Product_Name_EN
		{
			get
			{
				return this._Product_Name_EN;
			}
			set
			{
				if ((this._Product_Name_EN != value))
				{
					this._Product_Name_EN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Branch_Code", DbType="Int NOT NULL")]
		public int Branch_Code
		{
			get
			{
				return this._Branch_Code;
			}
			set
			{
				if ((this._Branch_Code != value))
				{
					this._Branch_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category_Code", DbType="Int")]
		public System.Nullable<int> Category_Code
		{
			get
			{
				return this._Category_Code;
			}
			set
			{
				if ((this._Category_Code != value))
				{
					this._Category_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Typical", DbType="Int")]
		public System.Nullable<int> Typical
		{
			get
			{
				return this._Typical;
			}
			set
			{
				if ((this._Typical != value))
				{
					this._Typical = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Money")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Promotions", DbType="Int")]
		public System.Nullable<int> Promotions
		{
			get
			{
				return this._Promotions;
			}
			set
			{
				if ((this._Promotions != value))
				{
					this._Promotions = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Promotions_Start_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Promotions_Start_Date
		{
			get
			{
				return this._Promotions_Start_Date;
			}
			set
			{
				if ((this._Promotions_Start_Date != value))
				{
					this._Promotions_Start_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Promotions_End_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Promotions_End_Date
		{
			get
			{
				return this._Promotions_End_Date;
			}
			set
			{
				if ((this._Promotions_End_Date != value))
				{
					this._Promotions_End_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inventory_Number", DbType="Int")]
		public System.Nullable<int> Inventory_Number
		{
			get
			{
				return this._Inventory_Number;
			}
			set
			{
				if ((this._Inventory_Number != value))
				{
					this._Inventory_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Order_Number", DbType="Int")]
		public System.Nullable<int> Order_Number
		{
			get
			{
				return this._Order_Number;
			}
			set
			{
				if ((this._Order_Number != value))
				{
					this._Order_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sort", DbType="Int")]
		public System.Nullable<int> Sort
		{
			get
			{
				return this._Sort;
			}
			set
			{
				if ((this._Sort != value))
				{
					this._Sort = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="NVarChar(100)")]
		public string Picture
		{
			get
			{
				return this._Picture;
			}
			set
			{
				if ((this._Picture != value))
				{
					this._Picture = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apply_Start_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Apply_Start_Date
		{
			get
			{
				return this._Apply_Start_Date;
			}
			set
			{
				if ((this._Apply_Start_Date != value))
				{
					this._Apply_Start_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apply_End_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Apply_End_Date
		{
			get
			{
				return this._Apply_End_Date;
			}
			set
			{
				if ((this._Apply_End_Date != value))
				{
					this._Apply_End_Date = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OD_ROLE")]
	public partial class OD_ROLE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Role_Code;
		
		private string _Role_Name;
		
		private string _Role_Name_EN;
		
		private System.Nullable<System.DateTime> _Apply_End_Date;
		
		private System.Nullable<System.DateTime> _Apply_Start_Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRole_CodeChanging(string value);
    partial void OnRole_CodeChanged();
    partial void OnRole_NameChanging(string value);
    partial void OnRole_NameChanged();
    partial void OnRole_Name_ENChanging(string value);
    partial void OnRole_Name_ENChanged();
    partial void OnApply_End_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnApply_End_DateChanged();
    partial void OnApply_Start_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnApply_Start_DateChanged();
    #endregion
		
		public OD_ROLE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role_Code", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Role_Code
		{
			get
			{
				return this._Role_Code;
			}
			set
			{
				if ((this._Role_Code != value))
				{
					this.OnRole_CodeChanging(value);
					this.SendPropertyChanging();
					this._Role_Code = value;
					this.SendPropertyChanged("Role_Code");
					this.OnRole_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Role_Name
		{
			get
			{
				return this._Role_Name;
			}
			set
			{
				if ((this._Role_Name != value))
				{
					this.OnRole_NameChanging(value);
					this.SendPropertyChanging();
					this._Role_Name = value;
					this.SendPropertyChanged("Role_Name");
					this.OnRole_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role_Name_EN", DbType="NVarChar(100)")]
		public string Role_Name_EN
		{
			get
			{
				return this._Role_Name_EN;
			}
			set
			{
				if ((this._Role_Name_EN != value))
				{
					this.OnRole_Name_ENChanging(value);
					this.SendPropertyChanging();
					this._Role_Name_EN = value;
					this.SendPropertyChanged("Role_Name_EN");
					this.OnRole_Name_ENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apply_End_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Apply_End_Date
		{
			get
			{
				return this._Apply_End_Date;
			}
			set
			{
				if ((this._Apply_End_Date != value))
				{
					this.OnApply_End_DateChanging(value);
					this.SendPropertyChanging();
					this._Apply_End_Date = value;
					this.SendPropertyChanged("Apply_End_Date");
					this.OnApply_End_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apply_Start_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Apply_Start_Date
		{
			get
			{
				return this._Apply_Start_Date;
			}
			set
			{
				if ((this._Apply_Start_Date != value))
				{
					this.OnApply_Start_DateChanging(value);
					this.SendPropertyChanging();
					this._Apply_Start_Date = value;
					this.SendPropertyChanged("Apply_Start_Date");
					this.OnApply_Start_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OR_FUNCTION")]
	public partial class OR_FUNCTION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Function_Code;
		
		private string _Function_Name;
		
		private string _Function_Name_EN;
		
		private System.Nullable<int> _Branch_Code;
		
		private string _Role_Code;
		
		private System.Nullable<System.DateTime> _Apply_End_Date;
		
		private System.Nullable<System.DateTime> _Apply_Start_Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFunction_CodeChanging(int value);
    partial void OnFunction_CodeChanged();
    partial void OnFunction_NameChanging(string value);
    partial void OnFunction_NameChanged();
    partial void OnFunction_Name_ENChanging(string value);
    partial void OnFunction_Name_ENChanged();
    partial void OnBranch_CodeChanging(System.Nullable<int> value);
    partial void OnBranch_CodeChanged();
    partial void OnRole_CodeChanging(string value);
    partial void OnRole_CodeChanged();
    partial void OnApply_End_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnApply_End_DateChanged();
    partial void OnApply_Start_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnApply_Start_DateChanged();
    #endregion
		
		public OR_FUNCTION()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Function_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Function_Code
		{
			get
			{
				return this._Function_Code;
			}
			set
			{
				if ((this._Function_Code != value))
				{
					this.OnFunction_CodeChanging(value);
					this.SendPropertyChanging();
					this._Function_Code = value;
					this.SendPropertyChanged("Function_Code");
					this.OnFunction_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Function_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Function_Name
		{
			get
			{
				return this._Function_Name;
			}
			set
			{
				if ((this._Function_Name != value))
				{
					this.OnFunction_NameChanging(value);
					this.SendPropertyChanging();
					this._Function_Name = value;
					this.SendPropertyChanged("Function_Name");
					this.OnFunction_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Function_Name_EN", DbType="VarChar(100)")]
		public string Function_Name_EN
		{
			get
			{
				return this._Function_Name_EN;
			}
			set
			{
				if ((this._Function_Name_EN != value))
				{
					this.OnFunction_Name_ENChanging(value);
					this.SendPropertyChanging();
					this._Function_Name_EN = value;
					this.SendPropertyChanged("Function_Name_EN");
					this.OnFunction_Name_ENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Branch_Code", DbType="Int")]
		public System.Nullable<int> Branch_Code
		{
			get
			{
				return this._Branch_Code;
			}
			set
			{
				if ((this._Branch_Code != value))
				{
					this.OnBranch_CodeChanging(value);
					this.SendPropertyChanging();
					this._Branch_Code = value;
					this.SendPropertyChanged("Branch_Code");
					this.OnBranch_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role_Code", DbType="NChar(10)")]
		public string Role_Code
		{
			get
			{
				return this._Role_Code;
			}
			set
			{
				if ((this._Role_Code != value))
				{
					this.OnRole_CodeChanging(value);
					this.SendPropertyChanging();
					this._Role_Code = value;
					this.SendPropertyChanged("Role_Code");
					this.OnRole_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apply_End_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Apply_End_Date
		{
			get
			{
				return this._Apply_End_Date;
			}
			set
			{
				if ((this._Apply_End_Date != value))
				{
					this.OnApply_End_DateChanging(value);
					this.SendPropertyChanging();
					this._Apply_End_Date = value;
					this.SendPropertyChanged("Apply_End_Date");
					this.OnApply_End_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apply_Start_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Apply_Start_Date
		{
			get
			{
				return this._Apply_Start_Date;
			}
			set
			{
				if ((this._Apply_Start_Date != value))
				{
					this.OnApply_Start_DateChanging(value);
					this.SendPropertyChanging();
					this._Apply_Start_Date = value;
					this.SendPropertyChanged("Apply_Start_Date");
					this.OnApply_Start_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OD_USER")]
	public partial class OD_USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserName;
		
		private string _Password;
		
		private int _Comp_Code;
		
		private string _Device_Token;
		
		private string _Branch_Code;
		
		private string _Role_Code;
		
		private string _Sector;
		
		private System.Nullable<System.DateTime> _Last_Login;
		
		private System.Nullable<System.DateTime> _Apply_End_Date;
		
		private System.Nullable<System.DateTime> _Apply_Start_Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnComp_CodeChanging(int value);
    partial void OnComp_CodeChanged();
    partial void OnDevice_TokenChanging(string value);
    partial void OnDevice_TokenChanged();
    partial void OnBranch_CodeChanging(string value);
    partial void OnBranch_CodeChanged();
    partial void OnRole_CodeChanging(string value);
    partial void OnRole_CodeChanged();
    partial void OnSectorChanging(string value);
    partial void OnSectorChanged();
    partial void OnLast_LoginChanging(System.Nullable<System.DateTime> value);
    partial void OnLast_LoginChanged();
    partial void OnApply_End_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnApply_End_DateChanged();
    partial void OnApply_Start_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnApply_Start_DateChanged();
    #endregion
		
		public OD_USER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comp_Code", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Comp_Code
		{
			get
			{
				return this._Comp_Code;
			}
			set
			{
				if ((this._Comp_Code != value))
				{
					this.OnComp_CodeChanging(value);
					this.SendPropertyChanging();
					this._Comp_Code = value;
					this.SendPropertyChanged("Comp_Code");
					this.OnComp_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Device_Token", DbType="VarChar(MAX)")]
		public string Device_Token
		{
			get
			{
				return this._Device_Token;
			}
			set
			{
				if ((this._Device_Token != value))
				{
					this.OnDevice_TokenChanging(value);
					this.SendPropertyChanging();
					this._Device_Token = value;
					this.SendPropertyChanged("Device_Token");
					this.OnDevice_TokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Branch_Code", DbType="VarChar(100)")]
		public string Branch_Code
		{
			get
			{
				return this._Branch_Code;
			}
			set
			{
				if ((this._Branch_Code != value))
				{
					this.OnBranch_CodeChanging(value);
					this.SendPropertyChanging();
					this._Branch_Code = value;
					this.SendPropertyChanged("Branch_Code");
					this.OnBranch_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role_Code", DbType="VarChar(50)")]
		public string Role_Code
		{
			get
			{
				return this._Role_Code;
			}
			set
			{
				if ((this._Role_Code != value))
				{
					this.OnRole_CodeChanging(value);
					this.SendPropertyChanging();
					this._Role_Code = value;
					this.SendPropertyChanged("Role_Code");
					this.OnRole_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sector", DbType="VarChar(50)")]
		public string Sector
		{
			get
			{
				return this._Sector;
			}
			set
			{
				if ((this._Sector != value))
				{
					this.OnSectorChanging(value);
					this.SendPropertyChanging();
					this._Sector = value;
					this.SendPropertyChanged("Sector");
					this.OnSectorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Login", DbType="Date")]
		public System.Nullable<System.DateTime> Last_Login
		{
			get
			{
				return this._Last_Login;
			}
			set
			{
				if ((this._Last_Login != value))
				{
					this.OnLast_LoginChanging(value);
					this.SendPropertyChanging();
					this._Last_Login = value;
					this.SendPropertyChanged("Last_Login");
					this.OnLast_LoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apply_End_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Apply_End_Date
		{
			get
			{
				return this._Apply_End_Date;
			}
			set
			{
				if ((this._Apply_End_Date != value))
				{
					this.OnApply_End_DateChanging(value);
					this.SendPropertyChanging();
					this._Apply_End_Date = value;
					this.SendPropertyChanged("Apply_End_Date");
					this.OnApply_End_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apply_Start_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Apply_Start_Date
		{
			get
			{
				return this._Apply_Start_Date;
			}
			set
			{
				if ((this._Apply_Start_Date != value))
				{
					this.OnApply_Start_DateChanging(value);
					this.SendPropertyChanging();
					this._Apply_Start_Date = value;
					this.SendPropertyChanged("Apply_Start_Date");
					this.OnApply_Start_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
